### ISSUE TITLE
Refreshing Clans Page after searching

### ISSUE THREAD

**Issue by RyanTonerCode** [negri/wotclans#14]
Upon applying a search to the clan data table, if the user refreshes the page it causes the datatable to still have the filter but the search box is cleared.

**Comment by negri** [comment]
Thanks, @RyanTonerCode!

I tried the patch, but still didn't work. So I put myself (again) to read datatables.net and found [this](https://datatables.net/reference/option/stateLoaded): they provide a callback after loading persisted settings, like paging and the search string. On this callback I configured to recover the string and put it on the search box.
